### ISSUE TITLE
Simple Homepate Vue3 Template 버전이 추가된다면 좋겠습니다.

### ISSUE THREAD

**Issue by Jadeu3** [eGovFramework/egovframe-template-simple-react#13]
Front-end 기술로 많이 사용되는 React 뿐만 아니라, Vue 의 경우에도 매우 널리 사용되고 있습니다.

Vue3용 Simple Homepage Template이 추가된다면 표준프레임워크 적용 시 

Front-end Framework 선택의 폭이 넓어져 좋을 것 같습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
