### ISSUE TITLE
Next.js (SSR), Typescript 지원 부탁드립니다.

### ISSUE THREAD

**Issue by princox** [eGovFramework/egovframe-template-simple-react#17]
요새 개발로 핫한 회사들은 모두 리액트 기반 프레임워크들을 사용합니다.

그 중에서는 여러 이유로 서버 사이드 렌더링을 하고자 Next.js를 사용하곤 하는데요.

전자정부프레임워크에서도 서버 사이드 렌더링과 타입스크립트를 지원하는 예제가 많이 있었으면 합니다.

앞으로 수 많은 프레임워크와 기술들이 도래할텐데, 그 때마다 프론트엔드단은 분리해서 여러 스택으로 붙일 수 있는 예제가 있다면

미래 많은 개발자분들이 여러 방향으로 커밋해주지 않을까요?

향후 전자정부프레임워크의 발전을 위해서 작은 의견 내봅니다.. :)

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 소정의 기념품과 함께 표준프레임워크 오픈커뮤니티에서 커피쿠폰을 같이 발송 드릴 예정입니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
