### ISSUE TITLE
VUE 템플릿 추가 건의

### ISSUE THREAD

**Issue by dr-hongjae** [eGovFramework/egovframe-template-simple-react#31]
### 연락처 Contact

hongjae30@gmail.com

### 추가 요청 기능명 Feature Name

vue 템플릿 추가 건의

### 기능 상세 설명 Feature Description

상당히 좋고 우수한 표준프레임워크에서도 드디어 리액트 템플릿을 만들어주셔서 건의드려봅니다.
유지보수를 하기에 공공기관에서는 JSP와 더불어 종종 vue도 채택되곤 하는 것 같습니다.

뷰는 간단하고 직관적인 문법과 구조를 가지고 있어 
이로 인해 개발 생산성이 향상되고, 필요한 기능들을 빠르게 구현할 수 있습니다.

단가를 맞추기에는 퍼블리셔 분들이 vue나 react 소스를 읽어야할 때가 있는데,
react보다 vue를 선호하는 경향이 있기도 합니다.

또 뷰는 가볍고 빠른 성능을 자랑합니다.
가상 DOM (Virtual DOM)을 사용하여 효율적인 렌더링을 구현하므로 큰 규모의 프로젝트에서도 높은 성능을 유지할 수 있습니다.

따라서 위와 같은 이유로 vue 템플릿 추가를 하는게 어떤지 건의드려봅니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위해 소중한 의견 감사합니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.
