### ISSUE TITLE
[Bug]: CI Icon 클릭 시 Github Actions로 이동되지 않고 있습니다.

### ISSUE THREAD

**Issue by taehyun-learn** [eGovFramework/egovframe-template-simple-react#37]
### 연락처 Contact

chris5207@naver.com

### 오류 내용 Error Description

README 의 빌드 확인 CI Icon 클릭 시 Actions로 이동이 되지 않고 있습니다.
![image](https://github.com/eGovFramework/egovframe-template-simple-react/actions/workflows/node.js.yml/badge.svg)

클릭 시 빌드 확인된 Github Actions 페이지로 이동이 되어야 할 것 같습니다.

### 오류 재현 방법 How to reproduce the error

1. Node.js CI Icon 클릭 
2. 단순 icon 파일 경로로 이동 됨

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

**Comment by lat230627** [comment]
Spring Security 깃허브 사이트 참고하면 좋을 것 같습니다. 
https://github.com/spring-projects/spring-security
https://github.com/spring-projects/spring-security/actions?query=workflow%3ACI

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위해 소중한 의견 감사합니다.
