### ISSUE TITLE
tailwind css 등 css 프레임워크 도입 건의

### ISSUE THREAD

**Issue by BELLORI** [eGovFramework/egovframe-template-simple-react#38]
### 연락처 Contact

bellori729@gmail.com 

### 추가 요청 기능명 Feature Name

css 프레임워크 도입 건의

### 기능 상세 설명 Feature Description

css 프레임워크 도입 건의합니다.

사전 정의된 유틸리티 클래스 세트를 따르면
코드베이스가 일관성을 유지하는 경향이 있으므로 대규모 프로젝트를 진행하는 팀에 특히 유용한 것으로 사료됩니다.
또  다양한 화면 크기에서 잘 작동하는 인터페이스를 쉽게 만들 수 있는 반응형 디자인 유틸리티가 포함되어 있습니다.
그 중 Tailwind는 강력한 커뮤니티와 생태계를 보유하고 있습니다.
수많은 플러그인, 확장 기능, 리소스를 사용할 수 있어 다른 도구 및 기술과 쉽게 통합할 수 있습니다.

따라서 tailwind css 적용 검토 건의합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위해 소중한 의견 감사합니다.
