### ISSUE TITLE
[기능요구(Feature)]: CRA > Vite build tool 변경 건의

### ISSUE THREAD

**Issue by taehyun-learn** [eGovFramework/egovframe-template-simple-react#39]
### 연락처 Contact

chris5207@naver.com

### 추가 요청 기능명 Feature Name

빌드 툴 변경 건의

### 기능 상세 설명 Feature Description

현재 react-template는 CRA가 빌드환경으로 되어있습니다.
최근 Vite를 통한 빌드 환경이  화두가 되고 있으며 아래 이미지는 최근 npm trends 입니다.
![image](https://github.com/eGovFramework/egovframe-template-simple-react/assets/19388823/b7856c39-e052-47fd-94e5-95ca2f544564)
CRA를 통해 설치되는 react-scripts보다 vite가 더 많이 사용되고 있으며,
내부 구현이 Rust로 구현되어 있어 CRA보다 Vite의 빌드 속도가 빨라 개발자가 더 편하게 개발 내용을 확인할 수 있습니다.
React template도 Vite로 빌드 될 수 있도록 건의 드립니다.

### 솔루션 상세 Solution Details

vite 관련 깃허브 주소는 https://github.com/vitejs/vite 이고 cookbook과 같은 다양한 예제를 https://github.com/vitejs/awesome-vite에서 찾아볼 수 있습니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위해 소중한 의견 감사합니다.
